# This file helps us easily spin up our Postgres database in local
# development (this is not meant to be used in production), bypassing the need
# to install and configure these services on our local machines.
version: '3'

services:
  postgres:
    container_name: quantumqa-postgres
    image: postgres:15-alpine
    ports:
      # We're using port 5433 to avoid any potential conflicts.
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quantumqa
      POSTGRES_PASSWORD: quantumqa
      POSTGRES_USER: quantumqa

  redis:
    container_name: quantumqa-redis
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
